apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  labels:
    app: {{ .Values.api.label }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector: 
    matchLabels:
      app: {{ .Values.api.name }}
  template:
    metadata:
      labels: 
        app: {{ .Values.api.name }}
    spec:
      containers:
      - name: {{ .Values.api.name }}
        image: {{ .Values.api.image }}
        imagePullPolicy: {{ .Values.api.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.api.containerPort }}